POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Fabio Akita", 
    "email": "akita.dev@gmail.com"
}

###
GET http://localhost:8080/users

###
DELETE http://localhost:8080/users/5