POST http://localhost:3000/users
Content-Type: application/json
   
{
    "name": "Carlos Alberto da Silva", 
    "email": "carlos.alberto232@gmail.com",
    "password": "123"
}


###
GET http://localhost:3000/users


###
PUT http://localhost:3000/users/


###
DELETE http://localhost:3000/users/31